#!/bin/bash
set -ex
docker run --rm -p 4000:4000 -v $(pwd)/book_sources:/gitbook onejar99/gitbook:light "gitbook init && gitbook install && gitbook build"
docker run --rm -p 8080:8080 -v $(pwd)/book_sources/_book:/home/app/public onejar99/nodejs-live-server:node12.16.1
